sudo: false
language: node_js
node_js:
- '0.8'
- '0.10'
- '0.12'
- '4'
- '6'
- '7'
matrix:
  fast_finish: true
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-install.bash)"
before_script:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-verify.bash)"
after_success:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  slack:
    secure: dEzEB6FLgOYsy+FtbJEwRjNOA3ZQMU8RChrAKKhwklDUrwkhLm8fkXZkJgoIysAAv8XD88u44ugRHiwzgPmwn0GUxQv27pTm96vugcNOskMx3ZtzD0m/4C7C0ErErD41X8v41QLzFPdVqcSRPE0XGtRIn54uYGxAOdnqC1f8GoM=
  email:
    recipients:
      secure: LxF5WOSPybYSkJ49qgNU5lVFMnGmsGcsRD+gXXZClcjw7zF8cojF9svLod0Fe79cfjddVyyQdJNbRc92VVphIs5rpVXdtYu4cjvoh1A1LOa3WcBIAjuXFrqPzCBhf/+Rzwz5NTk7aPAuOCjTJ0h+AtimeRZvpOXmFkd5oy+S/ec=
